services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    volumes:
      - hm_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080
volumes:
  hm_data:
